import type { Metadata } from "next";
import Providers from "@/providers/StoreProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import AosRegistry from "@/config/AosRegistry";
import ToastProvider from "@/providers/ToastProvider";
import React, { ReactNode, Suspense } from "react";
import AuthRedirectProvider from "@/providers/AuthRedirectProvider";

const inter = Inter({ subsets: ["greek"] });

export const metadata: Metadata = {
  title: "AI Jurist",
  description: "Generated by create next app",
  icons: { icon: "/favicon.svg" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>AI Jurist</title>
        <link rel="icon" href="/favicon.svg" sizes="any" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&family=Urbanist:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <AosRegistry />
        <Providers>
          <AuthRedirectProvider>
            <ToastProvider>
              <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
            </ToastProvider>
          </AuthRedirectProvider>
        </Providers>
      </body>
    </html>
  );
}
